#!/bin/bash 
# ft=sh

function xssh () 
{ 
    c=($(cat ~/.colorcombo |sort -R |head -1|sed 's/-/ /'));
    if [[ $SHELL = "/bin/bash" ]]; then
        fg=${c[0]};
        bg=${c[1]};
    else
        fg=${c[1]};
        bg=${c[2]};
    fi;
    XTOPTS='-fs 9 -geom 120x36';
    xt="xterm $XTOPTS -bg '#$bg' -fg '#$fg'";
    if [[ $# -ne 1 ]]; then
        _known_hosts_real -a -F '' '';
        host=$(zenity --list --title "Select Host" --column "host" ${COMPREPLY[@]});
        cmd="TERM=xterm $xt -T $fg-$bg-$1 -e ssh -Y $host";
        echo "$fg-$bg" > /tmp/colorcombo;
        echo "Executing CMD :: $cmd";
        eval $cmd &
    fi;
    cmd="TERM=xterm $xt -T $fg-$bg-$1 -e ssh -Y $1";
    echo "$fg-$bg" > /tmp/colorcombo;
    echo "Executing CMD :: $cmd";
    eval $cmd &
}


function addhosts()
{
	for i in {1..254}; do echo "192.168.183.$i vm$i" | sudo tee -a /etc/hosts; done
}


function f() {
	#function_body
    	find . -iname \*$1\*
}

function ex()
{
    if [[ -f $1 ]]; then
        case $1 in
            *.tar.bz2)   tar xjf $1  ;;
            *.tar.gz)    tar xzf $1  ;;
            *.bz2)       bunzip2 $1  ;;
            *.rar)       rar x $1    ;;
            *.gz)        gunzip $1   ;;
            *.tar)       tar xf $1   ;;
            *.tbz2)      tar xjf $1  ;;
            *.tgz)       tar xzf $1  ;;
            *.zip)       unzip $1    ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1     ;;
            *)           echo $1 cannot be extracted ;;
        esac
    else
        echo $1 is not a valid file
    fi
}

function wfuzz-beast()
{
    wfuzz -c -z file,/usr/share/wfuzz/wordlist/general/megabeast.txt --hc 400,403,404,000 --hw 4  -H "User-Agent: Mozilla"  "$1/FUZZ"
}

function urlencode() {
    # urlencode <string>
    hURL -U "$1" -s --nocolor
    return;
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done

    LC_COLLATE=$old_lc_collate
}

function urldecode() {
    # urldecode <string>

    local url_encoded="${1//+/ }"
    printf '%b' "${url_encoded//%/\\x}"
}


function mcd()
{
    mkdir -p $1
    cd $1
}

copy_shell_code()
{
    xclip -o |grep '"\\x' |awk -F'"' '{print $2}' | tr -d '\n' |xlip -i
}

function portnumber()
{
    cd /mnt/Dropbox/personal/myscripts/port-numbers
    awk -F, -v p=$1 -v pn=$2 '$3 == p && $2 == pn' service-names-port-numbers.csv
}

function gtfobins()
{
    firefox "https://gtfobins.github.io/gtfobins/$1/"
}

function f()
{
    find . -iname \*$1\*
}
